import { Geist, Geist_Mono } from "next/font/google";
import { Kanit } from 'next/font/google'
import './globals.css'
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kanit = Kanit({ 
  subsets: ['latin'],
  weight: ['300'],
  variable: '--font-kanit'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={kanit.variable}>
      <body className="bg-gray-50 text-gray-900 gradient-bg">
        <div className="mt-10">
          <Navbar></Navbar>
        </div>
        <main className="container mx-auto">{children}</main>
      </body>
    </html>
  );
}

